# Generated by Django 5.0.2 on 2024-09-20 13:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_management", "0002_userprofile_agent_organisation"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_agent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="is_organiser",
            field=models.BooleanField(default=True),
        ),
    ]
