# Generated by Django 5.0.2 on 2024-09-20 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_management", "0003_user_is_agent_user_is_organiser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="customer_management.agent",
            ),
        ),
    ]
