# Generated by Django 5.0.2 on 2024-09-20 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_management", "0004_alter_lead_agent"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="organisation",
            field=models.ForeignKey(
                default=7,
                on_delete=django.db.models.deletion.CASCADE,
                to="customer_management.userprofile",
            ),
            preserve_default=False,
        ),
    ]
