# Generated by Django 5.0.2 on 2024-09-21 07:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customer_management", "0006_alter_lead_agent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lead",
            name="agent",
        ),
        migrations.RemoveField(
            model_name="lead",
            name="organisation",
        ),
    ]
