# Generated by Django 5.0.2 on 2024-09-21 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_management", "0007_remove_lead_agent_remove_lead_organisation"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="customer_management.agent",
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="organisation",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="customer_management.userprofile",
            ),
            preserve_default=False,
        ),
    ]
