# Generated by Django 5.0.2 on 2024-09-23 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_management", "0010_category_organisation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="organisation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="customer_management.userprofile",
            ),
        ),
    ]
