# Generated by Django 5.0.2 on 2024-09-29 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_management", "0012_alter_lead_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="DetailsForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("details", models.TextField()),
            ],
        ),
    ]
