# Generated by Django 5.0.2 on 2024-09-29 12:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customer_management", "0013_detailsform"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="detailsform",
            name="details",
        ),
    ]
