# Generated by Django 5.0.2 on 2024-09-29 12:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customer_management", "0014_remove_detailsform_details"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DetailsForm",
        ),
    ]
