# Generated by Django 5.0.2 on 2024-09-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_management", "0015_delete_detailsform"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="email",
            field=models.EmailField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="agent",
            name="first_name",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="agent",
            name="last_name",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="agent",
            name="username",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
