# Generated by Django 5.0.2 on 2024-09-29 14:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "customer_management",
            "0016_agent_email_agent_first_name_agent_last_name_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.TextField()),
            ],
        ),
    ]
