# Generated by Django 5.0.2 on 2024-09-29 15:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_management", "0017_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="description",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
