# Generated by Django 5.0.2 on 2024-09-29 15:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_management", "0018_lead_description"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Status",
        ),
        migrations.AddField(
            model_name="agent",
            name="description",
            field=models.TextField(default="This is the agent description"),
            preserve_default=False,
        ),
    ]
