# Generated by Django 5.0.2 on 2024-09-29 17:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customer_management", "0019_delete_status_agent_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agent",
            name="email",
        ),
        migrations.RemoveField(
            model_name="agent",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="agent",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="agent",
            name="username",
        ),
    ]
