# Generated by Django 5.0.2 on 2024-09-29 17:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "customer_management",
            "0020_remove_agent_email_remove_agent_first_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="agent",
            name="first_name",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="agent",
            name="last_name",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="agent",
            name="username",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
