# Generated by Django 5.0.2 on 2024-09-29 17:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "customer_management",
            "0021_agent_email_agent_first_name_agent_last_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="agent",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="agent",
            name="first_name",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="agent",
            name="last_name",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="agent",
            name="username",
            field=models.CharField(max_length=30),
        ),
    ]
