# Generated by Django 5.0.2 on 2024-09-29 18:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "customer_management",
            "0022_alter_agent_email_alter_agent_first_name_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agent",
            name="email",
        ),
        migrations.RemoveField(
            model_name="agent",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="agent",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="agent",
            name="username",
        ),
    ]
